# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archemywebapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archemywebapp',
            new_name='ArchemywebappUser',
        ),
    ]
