package com.archemy.searchapp.model.entities;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:25:32 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AreasEOImpl extends AutoIncrementEntityImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    AreaId {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaId();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaId((Integer)value);
      }
    }
    ,
    AreaParentId {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaParentId();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaParentId((Integer)value);
      }
    }
    ,
    AreaOrderNo {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaOrderNo();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaOrderNo((String)value);
      }
    }
    ,
    AreaDepthLevel {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaDepthLevel();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaDepthLevel((Integer)value);
      }
    }
    ,
    DimensionId {
      public Object get(AreasEOImpl obj) {
        return obj.getDimensionId();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setDimensionId((Integer)value);
      }
    }
    ,
    AreaName {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaName();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaName((String)value);
      }
    }
    ,
    Areas {
      public Object get(AreasEOImpl obj) {
        return obj.getAreas();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    DimensionIdAreas {
      public Object get(AreasEOImpl obj) {
        return obj.getDimensionIdAreas();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setDimensionIdAreas((AreasEOImpl)value);
      }
    }
    ,
    AreaParentIdAreas {
      public Object get(AreasEOImpl obj) {
        return obj.getAreaParentIdAreas();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreaParentIdAreas((AreasEOImpl)value);
      }
    }
    ,
    Areas1 {
      public Object get(AreasEOImpl obj) {
        return obj.getAreas1();
      }

      public void put(AreasEOImpl obj, Object value) {
        obj.setAreas1((AreasEOImpl)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(AreasEOImpl object);

    public abstract void put(AreasEOImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int AREAID = AttributesEnum.AreaId.index();
  public static final int AREAPARENTID = AttributesEnum.AreaParentId.index();
  public static final int AREAORDERNO = AttributesEnum.AreaOrderNo.index();
  public static final int AREADEPTHLEVEL = AttributesEnum.AreaDepthLevel.index();
  public static final int DIMENSIONID = AttributesEnum.DimensionId.index();
  public static final int AREANAME = AttributesEnum.AreaName.index();
  public static final int AREAS = AttributesEnum.Areas.index();
  public static final int DIMENSIONIDAREAS = AttributesEnum.DimensionIdAreas.index();
  public static final int AREAPARENTIDAREAS = AttributesEnum.AreaParentIdAreas.index();
  public static final int AREAS1 = AttributesEnum.Areas1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public AreasEOImpl() {
  }


  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("com.archemy.searchapp.model.entities.AreasEO");
  }

  /**
   * Gets the attribute value for AreaId, using the alias name AreaId.
   * @return the value of AreaId
   */
  public Integer getAreaId() {
    return (Integer)getAttributeInternal(AREAID);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaId.
   * @param value value to set the AreaId
   */
  public void setAreaId(Integer value) {
    setAttributeInternal(AREAID, value);
  }

  /**
   * Gets the attribute value for AreaParentId, using the alias name AreaParentId.
   * @return the value of AreaParentId
   */
  public Integer getAreaParentId() {
    return (Integer)getAttributeInternal(AREAPARENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaParentId.
   * @param value value to set the AreaParentId
   */
  public void setAreaParentId(Integer value) {
    setAttributeInternal(AREAPARENTID, value);
  }

  /**
   * Gets the attribute value for AreaOrderNo, using the alias name AreaOrderNo.
   * @return the value of AreaOrderNo
   */
  public String getAreaOrderNo() {
    return (String)getAttributeInternal(AREAORDERNO);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaOrderNo.
   * @param value value to set the AreaOrderNo
   */
  public void setAreaOrderNo(String value) {
    setAttributeInternal(AREAORDERNO, value);
  }

  /**
   * Gets the attribute value for AreaDepthLevel, using the alias name AreaDepthLevel.
   * @return the value of AreaDepthLevel
   */
  public Integer getAreaDepthLevel() {
    return (Integer)getAttributeInternal(AREADEPTHLEVEL);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaDepthLevel.
   * @param value value to set the AreaDepthLevel
   */
  public void setAreaDepthLevel(Integer value) {
    setAttributeInternal(AREADEPTHLEVEL, value);
  }

  /**
   * Gets the attribute value for DimensionId, using the alias name DimensionId.
   * @return the value of DimensionId
   */
  public Integer getDimensionId() {
    return (Integer)getAttributeInternal(DIMENSIONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DimensionId.
   * @param value value to set the DimensionId
   */
  public void setDimensionId(Integer value) {
    setAttributeInternal(DIMENSIONID, value);
  }

  /**
   * Gets the attribute value for AreaName, using the alias name AreaName.
   * @return the value of AreaName
   */
  public String getAreaName() {
    return (String)getAttributeInternal(AREANAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaName.
   * @param value value to set the AreaName
   */
  public void setAreaName(String value) {
    setAttributeInternal(AREANAME, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getAreas() {
    return (RowIterator)getAttributeInternal(AREAS);
  }

  /**
   * @return the associated entity AreasEOImpl.
   */
  public AreasEOImpl getDimensionIdAreas() {
    return (AreasEOImpl)getAttributeInternal(DIMENSIONIDAREAS);
  }

  /**
   * Sets <code>value</code> as the associated entity AreasEOImpl.
   */
  public void setDimensionIdAreas(AreasEOImpl value) {
    setAttributeInternal(DIMENSIONIDAREAS, value);
  }


  /**
   * @return the associated entity AreasEOImpl.
   */
  public AreasEOImpl getAreaParentIdAreas() {
    return (AreasEOImpl)getAttributeInternal(AREAPARENTIDAREAS);
  }

  /**
   * Sets <code>value</code> as the associated entity AreasEOImpl.
   */
  public void setAreaParentIdAreas(AreasEOImpl value) {
    setAttributeInternal(AREAPARENTIDAREAS, value);
  }

  /**
   * @return the associated entity AreasEOImpl.
   */
  public AreasEOImpl getAreas1() {
    return (AreasEOImpl)getAttributeInternal(AREAS1);
  }

  /**
   * Sets <code>value</code> as the associated entity AreasEOImpl.
   */
  public void setAreas1(AreasEOImpl value) {
    setAttributeInternal(AREAS1, value);
  }

  /**
   * @param areaId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer areaId) {
    return new Key(new Object[]{areaId});
  }


}
