package com.archemy.searchapp.model.entities;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:26:35 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IadsEOImpl extends AutoIncrementEntityImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    IadId {
      public Object get(IadsEOImpl obj) {
        return obj.getIadId();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setIadId((Integer)value);
      }
    }
    ,
    IadName {
      public Object get(IadsEOImpl obj) {
        return obj.getIadName();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setIadName((String)value);
      }
    }
    ,
    IadType {
      public Object get(IadsEOImpl obj) {
        return obj.getIadType();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setIadType((String)value);
      }
    }
    ,
    DomainId {
      public Object get(IadsEOImpl obj) {
        return obj.getDomainId();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setDomainId((Integer)value);
      }
    }
    ,
    KadId {
      public Object get(IadsEOImpl obj) {
        return obj.getKadId();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setKadId((Integer)value);
      }
    }
    ,
    Iads {
      public Object get(IadsEOImpl obj) {
        return obj.getIads();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    KadIdIads {
      public Object get(IadsEOImpl obj) {
        return obj.getKadIdIads();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setKadIdIads((IadsEOImpl)value);
      }
    }
    ,
    Iads1 {
      public Object get(IadsEOImpl obj) {
        return obj.getIads1();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    DomainIdIads {
      public Object get(IadsEOImpl obj) {
        return obj.getDomainIdIads();
      }

      public void put(IadsEOImpl obj, Object value) {
        obj.setDomainIdIads((IadsEOImpl)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(IadsEOImpl object);

    public abstract void put(IadsEOImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int IADID = AttributesEnum.IadId.index();
  public static final int IADNAME = AttributesEnum.IadName.index();
  public static final int IADTYPE = AttributesEnum.IadType.index();
  public static final int DOMAINID = AttributesEnum.DomainId.index();
  public static final int KADID = AttributesEnum.KadId.index();
  public static final int IADS = AttributesEnum.Iads.index();
  public static final int KADIDIADS = AttributesEnum.KadIdIads.index();
  public static final int IADS1 = AttributesEnum.Iads1.index();
  public static final int DOMAINIDIADS = AttributesEnum.DomainIdIads.index();

  /**
   * This is the default constructor (do not remove).
   */
  public IadsEOImpl() {
  }

  /**
   * Gets the attribute value for IadId, using the alias name IadId.
   * @return the value of IadId
   */
  public Integer getIadId() {
    return (Integer)getAttributeInternal(IADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for IadId.
   * @param value value to set the IadId
   */
  public void setIadId(Integer value) {
    setAttributeInternal(IADID, value);
  }

  /**
   * Gets the attribute value for IadName, using the alias name IadName.
   * @return the value of IadName
   */
  public String getIadName() {
    return (String)getAttributeInternal(IADNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for IadName.
   * @param value value to set the IadName
   */
  public void setIadName(String value) {
    setAttributeInternal(IADNAME, value);
  }

  /**
   * Gets the attribute value for IadType, using the alias name IadType.
   * @return the value of IadType
   */
  public String getIadType() {
    return (String)getAttributeInternal(IADTYPE);
  }

  /**
   * Sets <code>value</code> as the attribute value for IadType.
   * @param value value to set the IadType
   */
  public void setIadType(String value) {
    setAttributeInternal(IADTYPE, value);
  }

  /**
   * Gets the attribute value for DomainId, using the alias name DomainId.
   * @return the value of DomainId
   */
  public Integer getDomainId() {
    return (Integer)getAttributeInternal(DOMAINID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DomainId.
   * @param value value to set the DomainId
   */
  public void setDomainId(Integer value) {
    setAttributeInternal(DOMAINID, value);
  }

  /**
   * Gets the attribute value for KadId, using the alias name KadId.
   * @return the value of KadId
   */
  public Integer getKadId() {
    return (Integer)getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadId.
   * @param value value to set the KadId
   */
  public void setKadId(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getIads() {
    return (RowIterator)getAttributeInternal(IADS);
  }

  /**
   * @return the associated entity IadsEOImpl.
   */
  public IadsEOImpl getKadIdIads() {
    return (IadsEOImpl)getAttributeInternal(KADIDIADS);
  }

  /**
   * Sets <code>value</code> as the associated entity IadsEOImpl.
   */
  public void setKadIdIads(IadsEOImpl value) {
    setAttributeInternal(KADIDIADS, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getIads1() {
    return (RowIterator)getAttributeInternal(IADS1);
  }

  /**
   * @return the associated entity IadsEOImpl.
   */
  public IadsEOImpl getDomainIdIads() {
    return (IadsEOImpl)getAttributeInternal(DOMAINIDIADS);
  }

  /**
   * Sets <code>value</code> as the associated entity IadsEOImpl.
   */
  public void setDomainIdIads(IadsEOImpl value) {
    setAttributeInternal(DOMAINIDIADS, value);
  }

  /**
   * @param iadId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer iadId) {
    return new Key(new Object[]{iadId});
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("com.archemy.searchapp.model.entities.IadsEO");
  }
}
