package com.archemy.searchapp.model.entities;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:26:49 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadDimensionsAreaEOImpl extends AutoIncrementEntityImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    Id {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getId();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setId((Integer)value);
      }
    }
    ,
    DimensionId {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getDimensionId();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setDimensionId((Integer)value);
      }
    }
    ,
    KadId {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getKadId();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setKadId((Integer)value);
      }
    }
    ,
    AreaId {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getAreaId();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAreaId((Integer)value);
      }
    }
    ,
    AreaParentId {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getAreaParentId();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAreaParentId((Integer)value);
      }
    }
    ,
    KadDimensionsArea {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getKadDimensionsArea();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    KadIdKadDimensionsArea {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getKadIdKadDimensionsArea();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setKadIdKadDimensionsArea((KadDimensionsAreaEOImpl)value);
      }
    }
    ,
    KadDimensionsArea1 {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getKadDimensionsArea1();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    DimensionIdKadDimensionsArea {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getDimensionIdKadDimensionsArea();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setDimensionIdKadDimensionsArea((KadDimensionsAreaEOImpl)value);
      }
    }
    ,
    KadDimensionsArea2 {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getKadDimensionsArea2();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    AreaIdKadDimensionsArea {
      public Object get(KadDimensionsAreaEOImpl obj) {
        return obj.getAreaIdKadDimensionsArea();
      }

      public void put(KadDimensionsAreaEOImpl obj, Object value) {
        obj.setAreaIdKadDimensionsArea((KadDimensionsAreaEOImpl)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KadDimensionsAreaEOImpl object);

    public abstract void put(KadDimensionsAreaEOImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int ID = AttributesEnum.Id.index();
  public static final int DIMENSIONID = AttributesEnum.DimensionId.index();
  public static final int KADID = AttributesEnum.KadId.index();
  public static final int AREAID = AttributesEnum.AreaId.index();
  public static final int AREAPARENTID = AttributesEnum.AreaParentId.index();
  public static final int KADDIMENSIONSAREA = AttributesEnum.KadDimensionsArea.index();
  public static final int KADIDKADDIMENSIONSAREA = AttributesEnum.KadIdKadDimensionsArea.index();
  public static final int KADDIMENSIONSAREA1 = AttributesEnum.KadDimensionsArea1.index();
  public static final int DIMENSIONIDKADDIMENSIONSAREA = AttributesEnum.DimensionIdKadDimensionsArea.index();
  public static final int KADDIMENSIONSAREA2 = AttributesEnum.KadDimensionsArea2.index();
  public static final int AREAIDKADDIMENSIONSAREA = AttributesEnum.AreaIdKadDimensionsArea.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KadDimensionsAreaEOImpl() {
  }

  /**
   * Gets the attribute value for Id, using the alias name Id.
   * @return the value of Id
   */
  public Integer getId() {
    return (Integer)getAttributeInternal(ID);
  }

  /**
   * Sets <code>value</code> as the attribute value for Id.
   * @param value value to set the Id
   */
  public void setId(Integer value) {
    setAttributeInternal(ID, value);
  }

  /**
   * Gets the attribute value for DimensionId, using the alias name DimensionId.
   * @return the value of DimensionId
   */
  public Integer getDimensionId() {
    return (Integer)getAttributeInternal(DIMENSIONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DimensionId.
   * @param value value to set the DimensionId
   */
  public void setDimensionId(Integer value) {
    setAttributeInternal(DIMENSIONID, value);
  }

  /**
   * Gets the attribute value for KadId, using the alias name KadId.
   * @return the value of KadId
   */
  public Integer getKadId() {
    return (Integer)getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadId.
   * @param value value to set the KadId
   */
  public void setKadId(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * Gets the attribute value for AreaId, using the alias name AreaId.
   * @return the value of AreaId
   */
  public Integer getAreaId() {
    return (Integer)getAttributeInternal(AREAID);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaId.
   * @param value value to set the AreaId
   */
  public void setAreaId(Integer value) {
    setAttributeInternal(AREAID, value);
  }

  /**
   * Gets the attribute value for AreaParentId, using the alias name AreaParentId.
   * @return the value of AreaParentId
   */
  public Integer getAreaParentId() {
    return (Integer)getAttributeInternal(AREAPARENTID);
  }

  /**
   * Sets <code>value</code> as the attribute value for AreaParentId.
   * @param value value to set the AreaParentId
   */
  public void setAreaParentId(Integer value) {
    setAttributeInternal(AREAPARENTID, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getKadDimensionsArea() {
    return (RowIterator)getAttributeInternal(KADDIMENSIONSAREA);
  }

  /**
   * @return the associated entity KadDimensionsAreaEOImpl.
   */
  public KadDimensionsAreaEOImpl getKadIdKadDimensionsArea() {
    return (KadDimensionsAreaEOImpl)getAttributeInternal(KADIDKADDIMENSIONSAREA);
  }

  /**
   * Sets <code>value</code> as the associated entity KadDimensionsAreaEOImpl.
   */
  public void setKadIdKadDimensionsArea(KadDimensionsAreaEOImpl value) {
    setAttributeInternal(KADIDKADDIMENSIONSAREA, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getKadDimensionsArea1() {
    return (RowIterator)getAttributeInternal(KADDIMENSIONSAREA1);
  }

  /**
   * @return the associated entity KadDimensionsAreaEOImpl.
   */
  public KadDimensionsAreaEOImpl getDimensionIdKadDimensionsArea() {
    return (KadDimensionsAreaEOImpl)getAttributeInternal(DIMENSIONIDKADDIMENSIONSAREA);
  }

  /**
   * Sets <code>value</code> as the associated entity KadDimensionsAreaEOImpl.
   */
  public void setDimensionIdKadDimensionsArea(KadDimensionsAreaEOImpl value) {
    setAttributeInternal(DIMENSIONIDKADDIMENSIONSAREA, value);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getKadDimensionsArea2() {
    return (RowIterator)getAttributeInternal(KADDIMENSIONSAREA2);
  }

  /**
   * @return the associated entity KadDimensionsAreaEOImpl.
   */
  public KadDimensionsAreaEOImpl getAreaIdKadDimensionsArea() {
    return (KadDimensionsAreaEOImpl)getAttributeInternal(AREAIDKADDIMENSIONSAREA);
  }

  /**
   * Sets <code>value</code> as the associated entity KadDimensionsAreaEOImpl.
   */
  public void setAreaIdKadDimensionsArea(KadDimensionsAreaEOImpl value) {
    setAttributeInternal(AREAIDKADDIMENSIONSAREA, value);
  }

  /**
   * @param id key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer id) {
    return new Key(new Object[]{id});
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("com.archemy.searchapp.model.entities.KadDimensionsAreaEO");
  }
}
