package com.archemy.searchapp.model.entities;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 14 00:15:07 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadRegistrationEOImpl extends AutoIncrementEntityImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    UserId {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getUserId();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setUserId((String)value);
      }
    }
    ,
    Id {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getId();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setId((Integer)value);
      }
    }
    ,
    KadId {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getKadId();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setKadId((Integer)value);
      }
    }
    ,
    MaturityRating {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getMaturityRating();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setMaturityRating((Integer)value);
      }
    }
    ,
    DeploymentStatus {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getDeploymentStatus();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setDeploymentStatus((String)value);
      }
    }
    ,
    ApplicabilityExtent {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getApplicabilityExtent();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setApplicabilityExtent((String)value);
      }
    }
    ,
    BenefitRating {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getBenefitRating();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setBenefitRating((Integer)value);
      }
    }
    ,
    Comments {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getComments();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setComments((String)value);
      }
    }
    ,
    KadRegistration {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getKadRegistration();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    KadIdKadRegistration {
      public Object get(KadRegistrationEOImpl obj) {
        return obj.getKadIdKadRegistration();
      }

      public void put(KadRegistrationEOImpl obj, Object value) {
        obj.setKadIdKadRegistration((KadRegistrationEOImpl)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KadRegistrationEOImpl object);

    public abstract void put(KadRegistrationEOImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }
  public static final int USERID = AttributesEnum.UserId.index();
  public static final int ID = AttributesEnum.Id.index();
  public static final int KADID = AttributesEnum.KadId.index();
  public static final int MATURITYRATING = AttributesEnum.MaturityRating.index();
  public static final int DEPLOYMENTSTATUS = AttributesEnum.DeploymentStatus.index();
  public static final int APPLICABILITYEXTENT = AttributesEnum.ApplicabilityExtent.index();
  public static final int BENEFITRATING = AttributesEnum.BenefitRating.index();
  public static final int COMMENTS = AttributesEnum.Comments.index();
  public static final int KADREGISTRATION = AttributesEnum.KadRegistration.index();
  public static final int KADIDKADREGISTRATION = AttributesEnum.KadIdKadRegistration.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KadRegistrationEOImpl() {
  }

  /**
   * Gets the attribute value for UserId, using the alias name UserId.
   * @return the value of UserId
   */
  public String getUserId() {
    return (String)getAttributeInternal(USERID);
  }

  /**
   * Sets <code>value</code> as the attribute value for UserId.
   * @param value value to set the UserId
   */
  public void setUserId(String value) {
    setAttributeInternal(USERID, value);
  }

  /**
   * Gets the attribute value for Id, using the alias name Id.
   * @return the value of Id
   */
  public Integer getId() {
    return (Integer)getAttributeInternal(ID);
  }

  /**
   * Sets <code>value</code> as the attribute value for Id.
   * @param value value to set the Id
   */
  public void setId(Integer value) {
    setAttributeInternal(ID, value);
  }

  /**
   * Gets the attribute value for KadId, using the alias name KadId.
   * @return the value of KadId
   */
  public Integer getKadId() {
    return (Integer)getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadId.
   * @param value value to set the KadId
   */
  public void setKadId(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * Gets the attribute value for MaturityRating, using the alias name MaturityRating.
   * @return the value of MaturityRating
   */
  public Integer getMaturityRating() {
    return (Integer)getAttributeInternal(MATURITYRATING);
  }

  /**
   * Sets <code>value</code> as the attribute value for MaturityRating.
   * @param value value to set the MaturityRating
   */
  public void setMaturityRating(Integer value) {
    setAttributeInternal(MATURITYRATING, value);
  }

  /**
   * Gets the attribute value for DeploymentStatus, using the alias name DeploymentStatus.
   * @return the value of DeploymentStatus
   */
  public String getDeploymentStatus() {
    return (String)getAttributeInternal(DEPLOYMENTSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for DeploymentStatus.
   * @param value value to set the DeploymentStatus
   */
  public void setDeploymentStatus(String value) {
    setAttributeInternal(DEPLOYMENTSTATUS, value);
  }

  /**
   * Gets the attribute value for ApplicabilityExtent, using the alias name ApplicabilityExtent.
   * @return the value of ApplicabilityExtent
   */
  public String getApplicabilityExtent() {
    return (String)getAttributeInternal(APPLICABILITYEXTENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for ApplicabilityExtent.
   * @param value value to set the ApplicabilityExtent
   */
  public void setApplicabilityExtent(String value) {
    setAttributeInternal(APPLICABILITYEXTENT, value);
  }

  /**
   * Gets the attribute value for BenefitRating, using the alias name BenefitRating.
   * @return the value of BenefitRating
   */
  public Integer getBenefitRating() {
    return (Integer)getAttributeInternal(BENEFITRATING);
  }

  /**
   * Sets <code>value</code> as the attribute value for BenefitRating.
   * @param value value to set the BenefitRating
   */
  public void setBenefitRating(Integer value) {
    setAttributeInternal(BENEFITRATING, value);
  }

  /**
   * Gets the attribute value for Comments, using the alias name Comments.
   * @return the value of Comments
   */
  public String getComments() {
    return (String)getAttributeInternal(COMMENTS);
  }

  /**
   * Sets <code>value</code> as the attribute value for Comments.
   * @param value value to set the Comments
   */
  public void setComments(String value) {
    setAttributeInternal(COMMENTS, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getKadRegistration() {
    return (RowIterator)getAttributeInternal(KADREGISTRATION);
  }

  /**
   * @return the associated entity KadRegistrationEOImpl.
   */
  public KadRegistrationEOImpl getKadIdKadRegistration() {
    return (KadRegistrationEOImpl)getAttributeInternal(KADIDKADREGISTRATION);
  }

  /**
   * Sets <code>value</code> as the associated entity KadRegistrationEOImpl.
   */
  public void setKadIdKadRegistration(KadRegistrationEOImpl value) {
    setAttributeInternal(KADIDKADREGISTRATION, value);
  }

  /**
   * @param id key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer id) {
    return new Key(new Object[]{id});
  }

  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("com.archemy.searchapp.model.entities.KadRegistrationEO");
  }
}
