package com.archemy.searchapp.model.entities;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:27:03 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadsEOImpl extends AutoIncrementEntityImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    KadId {
      public Object get(KadsEOImpl obj) {
        return obj.getKadId();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setKadId((Integer)value);
      }
    }
    ,
    KadName {
      public Object get(KadsEOImpl obj) {
        return obj.getKadName();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setKadName((String)value);
      }
    }
    ,
    DomainId {
      public Object get(KadsEOImpl obj) {
        return obj.getDomainId();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setDomainId((Integer)value);
      }
    }
    ,
    KadLink {
      public Object get(KadsEOImpl obj) {
        return obj.getKadLink();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setKadLink((String)value);
      }
    }
    ,
    KadLinkPublic {
      public Object get(KadsEOImpl obj) {
        return obj.getKadLinkPublic();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setKadLinkPublic((String)value);
      }
    }
    ,
    KadHitCounter {
      public Object get(KadsEOImpl obj) {
        return obj.getKadHitCounter();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setKadHitCounter((Integer)value);
      }
    }
    ,
    RecurringBusProblemId {
      public Object get(KadsEOImpl obj) {
        return obj.getRecurringBusProblemId();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setRecurringBusProblemId((Integer)value);
      }
    }
    ,
    Kads {
      public Object get(KadsEOImpl obj) {
        return obj.getKads();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    DomainIdKads {
      public Object get(KadsEOImpl obj) {
        return obj.getDomainIdKads();
      }

      public void put(KadsEOImpl obj, Object value) {
        obj.setDomainIdKads((KadsEOImpl)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KadsEOImpl object);

    public abstract void put(KadsEOImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int KADID = AttributesEnum.KadId.index();
  public static final int KADNAME = AttributesEnum.KadName.index();
  public static final int DOMAINID = AttributesEnum.DomainId.index();
  public static final int KADLINK = AttributesEnum.KadLink.index();
  public static final int KADLINKPUBLIC = AttributesEnum.KadLinkPublic.index();
  public static final int KADHITCOUNTER = AttributesEnum.KadHitCounter.index();
  public static final int RECURRINGBUSPROBLEMID = AttributesEnum.RecurringBusProblemId.index();
  public static final int KADS = AttributesEnum.Kads.index();
  public static final int DOMAINIDKADS = AttributesEnum.DomainIdKads.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KadsEOImpl() {
  }


  /**
   * @return the definition object for this instance class.
   */
  public static synchronized EntityDefImpl getDefinitionObject() {
    return EntityDefImpl.findDefObject("com.archemy.searchapp.model.entities.KadsEO");
  }

  /**
   * Gets the attribute value for KadId, using the alias name KadId.
   * @return the value of KadId
   */
  public Integer getKadId() {
    return (Integer)getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadId.
   * @param value value to set the KadId
   */
  public void setKadId(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * Gets the attribute value for KadName, using the alias name KadName.
   * @return the value of KadName
   */
  public String getKadName() {
    return (String)getAttributeInternal(KADNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadName.
   * @param value value to set the KadName
   */
  public void setKadName(String value) {
    setAttributeInternal(KADNAME, value);
  }

  /**
   * Gets the attribute value for DomainId, using the alias name DomainId.
   * @return the value of DomainId
   */
  public Integer getDomainId() {
    return (Integer)getAttributeInternal(DOMAINID);
  }

  /**
   * Sets <code>value</code> as the attribute value for DomainId.
   * @param value value to set the DomainId
   */
  public void setDomainId(Integer value) {
    setAttributeInternal(DOMAINID, value);
  }

  /**
   * Gets the attribute value for KadLink, using the alias name KadLink.
   * @return the value of KadLink
   */
  public String getKadLink() {
    return (String)getAttributeInternal(KADLINK);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadLink.
   * @param value value to set the KadLink
   */
  public void setKadLink(String value) {
    setAttributeInternal(KADLINK, value);
  }

  /**
   * Gets the attribute value for KadLinkPublic, using the alias name KadLinkPublic.
   * @return the value of KadLinkPublic
   */
  public String getKadLinkPublic() {
    return (String)getAttributeInternal(KADLINKPUBLIC);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadLinkPublic.
   * @param value value to set the KadLinkPublic
   */
  public void setKadLinkPublic(String value) {
    setAttributeInternal(KADLINKPUBLIC, value);
  }

  /**
   * Gets the attribute value for KadHitCounter, using the alias name KadHitCounter.
   * @return the value of KadHitCounter
   */
  public Integer getKadHitCounter() {
    return (Integer)getAttributeInternal(KADHITCOUNTER);
  }

  /**
   * Sets <code>value</code> as the attribute value for KadHitCounter.
   * @param value value to set the KadHitCounter
   */
  public void setKadHitCounter(Integer value) {
    setAttributeInternal(KADHITCOUNTER, value);
  }


  /**
   * Gets the attribute value for RecurringBusProblemId, using the alias name RecurringBusProblemId.
   * @return the value of RecurringBusProblemId
   */
  public Integer getRecurringBusProblemId() {
    return (Integer)getAttributeInternal(RECURRINGBUSPROBLEMID);
  }

  /**
   * Sets <code>value</code> as the attribute value for RecurringBusProblemId.
   * @param value value to set the RecurringBusProblemId
   */
  public void setRecurringBusProblemId(Integer value) {
    setAttributeInternal(RECURRINGBUSPROBLEMID, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }

  /**
   * @return the associated entity oracle.jbo.RowIterator.
   */
  public RowIterator getKads() {
    return (RowIterator)getAttributeInternal(KADS);
  }

  /**
   * @return the associated entity KadsEOImpl.
   */
  public KadsEOImpl getDomainIdKads() {
    return (KadsEOImpl)getAttributeInternal(DOMAINIDKADS);
  }

  /**
   * Sets <code>value</code> as the associated entity KadsEOImpl.
   */
  public void setDomainIdKads(KadsEOImpl value) {
    setAttributeInternal(DOMAINIDKADS, value);
  }

  /**
   * @param kadId key constituent

   * @return a Key object based on given key constituents.
   */
  public static Key createPrimaryKey(Integer kadId) {
    return new Key(new Object[]{kadId});
  }


}
