package com.archemy.searchapp.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 15 21:18:14 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CustomerInfoVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public CustomerInfoVOImpl() {
  }

  /**
   * Returns the bind variable value for bUserId.
   * @return bind variable value for bUserId
   */
  public String getbUserId() {
    return (String)getNamedWhereClauseParam("bUserId");
  }

  /**
   * Sets <code>value</code> for bind variable bUserId.
   * @param value value to bind as bUserId
   */
  public void setbUserId(String value) {
    setNamedWhereClauseParam("bUserId", value);
  }
}
