package com.archemy.searchapp.model.queries;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 18:55:40 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KADDimensionsAreaTempVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    DimensionId {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getDimensionId();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setDimensionId((Integer)value);
      }
    }
    ,
    AreaChildId {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getAreaChildId();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAreaChildId((Integer)value);
      }
    }
    ,
    AreaId {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getAreaId();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAreaId((Integer)value);
      }
    }
    ,
    Weight {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getWeight();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setWeight((Integer)value);
      }
    }
    ,
    Closeness {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getCloseness();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setCloseness((Integer)value);
      }
    }
    ,
    UUID {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getUUID();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setUUID((String)value);
      }
    }
    ,
    DimensionsFilteredByDomainVO1 {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getDimensionsFilteredByDomainVO1();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    AreaChildLookupVO1 {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getAreaChildLookupVO1();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    ParentAreaIdLookupVO1 {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getParentAreaIdLookupVO1();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ,
    ParentAreaIdLookupProgVO1 {
      public Object get(KADDimensionsAreaTempVORowImpl obj) {
        return obj.getParentAreaIdLookupProgVO1();
      }

      public void put(KADDimensionsAreaTempVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KADDimensionsAreaTempVORowImpl object);

    public abstract void put(KADDimensionsAreaTempVORowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DIMENSIONID = AttributesEnum.DimensionId.index();
  public static final int AREACHILDID = AttributesEnum.AreaChildId.index();
  public static final int AREAID = AttributesEnum.AreaId.index();
  public static final int WEIGHT = AttributesEnum.Weight.index();
  public static final int CLOSENESS = AttributesEnum.Closeness.index();
  public static final int UUID = AttributesEnum.UUID.index();
  public static final int DIMENSIONSFILTEREDBYDOMAINVO1 = AttributesEnum.DimensionsFilteredByDomainVO1.index();
  public static final int AREACHILDLOOKUPVO1 = AttributesEnum.AreaChildLookupVO1.index();
  public static final int PARENTAREAIDLOOKUPVO1 = AttributesEnum.ParentAreaIdLookupVO1.index();
  public static final int PARENTAREAIDLOOKUPPROGVO1 = AttributesEnum.ParentAreaIdLookupProgVO1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KADDimensionsAreaTempVORowImpl() {
  }

  /**
   * Gets the attribute value for the calculated attribute DimensionId.
   * @return the DimensionId
   */
  public Integer getDimensionId() {
    return (Integer) getAttributeInternal(DIMENSIONID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DimensionId.
   * @param value value to set the  DimensionId
   */
  public void setDimensionId(Integer value) {
    setAttributeInternal(DIMENSIONID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AreaChildId.
   * @return the AreaChildId
   */
  public Integer getAreaChildId() {
    return (Integer) getAttributeInternal(AREACHILDID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AreaChildId.
   * @param value value to set the  AreaChildId
   */
  public void setAreaChildId(Integer value) {
    setAttributeInternal(AREACHILDID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AreaId.
   * @return the AreaId
   */
  public Integer getAreaId() {
    return (Integer) getAttributeInternal(AREAID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AreaId.
   * @param value value to set the  AreaId
   */
  public void setAreaId(Integer value) {
    setAttributeInternal(AREAID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Weight.
   * @return the Weight
   */
  public Integer getWeight() {
    return (Integer) getAttributeInternal(WEIGHT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Weight.
   * @param value value to set the  Weight
   */
  public void setWeight(Integer value) {
    setAttributeInternal(WEIGHT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Closeness.
   * @return the Closeness
   */
  public Integer getCloseness() {
    return (Integer) getAttributeInternal(CLOSENESS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Closeness.
   * @param value value to set the  Closeness
   */
  public void setCloseness(Integer value) {
    setAttributeInternal(CLOSENESS, value);
  }


  /**
   * Gets the attribute value for the calculated attribute UUID.
   * @return the UUID
   */
  public String getUUID() {
    return (String) getAttributeInternal(UUID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute UUID.
   * @param value value to set the  UUID
   */
  public void setUUID(String value) {
    setAttributeInternal(UUID, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> DimensionsFilteredByDomainVO1.
   */
  public RowSet getDimensionsFilteredByDomainVO1() {
    return (RowSet)getAttributeInternal(DIMENSIONSFILTEREDBYDOMAINVO1);
  }


  /**
   * Gets the view accessor <code>RowSet</code> AreaChildLookupVO1.
   */
  public RowSet getAreaChildLookupVO1() {
    return (RowSet)getAttributeInternal(AREACHILDLOOKUPVO1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> ParentAreaIdLookupVO1.
   */
  public RowSet getParentAreaIdLookupVO1() {
    return (RowSet)getAttributeInternal(PARENTAREAIDLOOKUPVO1);
  }

  /**
   * Gets the view accessor <code>RowSet</code> ParentAreaIdLookupProgVO1.
   */
  public RowSet getParentAreaIdLookupProgVO1() {
    return (RowSet)getAttributeInternal(PARENTAREAIDLOOKUPPROGVO1);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
