package com.archemy.searchapp.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 14:52:22 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadDimensionsAreaVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public KadDimensionsAreaVOImpl() {
  }
}
