package com.archemy.searchapp.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 15:39:44 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadsVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public KadsVOImpl() {
  }

  /**
   * Returns the variable value for bDomainId.
   * @return variable value for bDomainId
   */
  public Integer getbDomainId() {
    return (Integer)ensureVariableManager().getVariableValue("bDomainId");
  }

  /**
   * Sets <code>value</code> for variable bDomainId.
   * @param value value to bind as bDomainId
   */
  public void setbDomainId(Integer value) {
    ensureVariableManager().setVariableValue("bDomainId", value);
  }
}
