package com.archemy.searchapp.model.queries;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 25 17:53:34 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadSearchTransVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    KadID {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getKadID();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setKadID((Integer)value);
      }
    }
    ,
    KadLink {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getKadLink();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setKadLink((String)value);
      }
    }
    ,
    Score {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getScore();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setScore((Integer)value);
      }
    }
    ,
    DomainName {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getDomainName();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setDomainName((String)value);
      }
    }
    ,
    KadName {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getKadName();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setKadName((String)value);
      }
    }
    ,
    KadLinkPublic {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getKadLinkPublic();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setKadLinkPublic((String)value);
      }
    }
    ,
    HitCounter {
      public Object get(KadSearchTransVORowImpl obj) {
        return obj.getHitCounter();
      }

      public void put(KadSearchTransVORowImpl obj, Object value) {
        obj.setHitCounter((Integer)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KadSearchTransVORowImpl object);

    public abstract void put(KadSearchTransVORowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }

  public static final int KADID = AttributesEnum.KadID.index();
  public static final int KADLINK = AttributesEnum.KadLink.index();
  public static final int SCORE = AttributesEnum.Score.index();
  public static final int DOMAINNAME = AttributesEnum.DomainName.index();
  public static final int KADNAME = AttributesEnum.KadName.index();
  public static final int KADLINKPUBLIC = AttributesEnum.KadLinkPublic.index();
  public static final int HITCOUNTER = AttributesEnum.HitCounter.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KadSearchTransVORowImpl() {
  }

  /**
   * Gets the attribute value for the calculated attribute KadID.
   * @return the KadID
   */
  public Integer getKadID() {
    return (Integer) getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadID.
   * @param value value to set the  KadID
   */
  public void setKadID(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadLink.
   * @return the KadLink
   */
  public String getKadLink() {
    return (String) getAttributeInternal(KADLINK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadLink.
   * @param value value to set the  KadLink
   */
  public void setKadLink(String value) {
    setAttributeInternal(KADLINK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Score.
   * @return the Score
   */
  public Integer getScore() {
    return (Integer) getAttributeInternal(SCORE);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Score.
   * @param value value to set the  Score
   */
  public void setScore(Integer value) {
    setAttributeInternal(SCORE, value);
  }

  /**
   * Gets the attribute value for the calculated attribute DomainName.
   * @return the DomainName
   */
  public String getDomainName() {
    return (String) getAttributeInternal(DOMAINNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DomainName.
   * @param value value to set the  DomainName
   */
  public void setDomainName(String value) {
    setAttributeInternal(DOMAINNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadName.
   * @return the KadName
   */
  public String getKadName() {
    return (String) getAttributeInternal(KADNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadName.
   * @param value value to set the  KadName
   */
  public void setKadName(String value) {
    setAttributeInternal(KADNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadLinkPublic.
   * @return the KadLinkPublic
   */
  public String getKadLinkPublic() {
    return (String) getAttributeInternal(KADLINKPUBLIC);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadLinkPublic.
   * @param value value to set the  KadLinkPublic
   */
  public void setKadLinkPublic(String value) {
    setAttributeInternal(KADLINKPUBLIC, value);
  }


  /**
   * Gets the attribute value for the calculated attribute HitCounter.
   * @return the HitCounter
   */
  public Integer getHitCounter() {
    return (Integer) getAttributeInternal(HITCOUNTER);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute HitCounter.
   * @param value value to set the  HitCounter
   */
  public void setHitCounter(Integer value) {
    setAttributeInternal(HITCOUNTER, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
