package com.archemy.searchapp.model.queries;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:29:15 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadTempVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    KadName {
      public Object get(KadTempVORowImpl obj) {
        return obj.getKadName();
      }

      public void put(KadTempVORowImpl obj, Object value) {
        obj.setKadName((String)value);
      }
    }
    ,
    KadLink {
      public Object get(KadTempVORowImpl obj) {
        return obj.getKadLink();
      }

      public void put(KadTempVORowImpl obj, Object value) {
        obj.setKadLink((String)value);
      }
    }
    ,
    KadPublicLink {
      public Object get(KadTempVORowImpl obj) {
        return obj.getKadPublicLink();
      }

      public void put(KadTempVORowImpl obj, Object value) {
        obj.setKadPublicLink((String)value);
      }
    }
    ,
    Business_problem {
      public Object get(KadTempVORowImpl obj) {
        return obj.getBusiness_problem();
      }

      public void put(KadTempVORowImpl obj, Object value) {
        obj.setBusiness_problem((Integer)value);
      }
    }
    ,
    BusinessProblemLookupVO1 {
      public Object get(KadTempVORowImpl obj) {
        return obj.getBusinessProblemLookupVO1();
      }

      public void put(KadTempVORowImpl obj, Object value) {
        obj.setAttributeInternal(index(), value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(KadTempVORowImpl object);

    public abstract void put(KadTempVORowImpl object, Object value);

    public int index() {
      return AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int KADNAME = AttributesEnum.KadName.index();
  public static final int KADLINK = AttributesEnum.KadLink.index();
  public static final int KADPUBLICLINK = AttributesEnum.KadPublicLink.index();
  public static final int BUSINESS_PROBLEM = AttributesEnum.Business_problem.index();
  public static final int BUSINESSPROBLEMLOOKUPVO1 = AttributesEnum.BusinessProblemLookupVO1.index();

  /**
   * This is the default constructor (do not remove).
   */
  public KadTempVORowImpl() {
  }

  /**
   * Gets the attribute value for the calculated attribute KadName.
   * @return the KadName
   */
  public String getKadName() {
    return (String) getAttributeInternal(KADNAME);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadName.
   * @param value value to set the  KadName
   */
  public void setKadName(String value) {
    setAttributeInternal(KADNAME, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadLink.
   * @return the KadLink
   */
  public String getKadLink() {
    return (String) getAttributeInternal(KADLINK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadLink.
   * @param value value to set the  KadLink
   */
  public void setKadLink(String value) {
    setAttributeInternal(KADLINK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadPublicLink.
   * @return the KadPublicLink
   */
  public String getKadPublicLink() {
    return (String) getAttributeInternal(KADPUBLICLINK);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadPublicLink.
   * @param value value to set the  KadPublicLink
   */
  public void setKadPublicLink(String value) {
    setAttributeInternal(KADPUBLICLINK, value);
  }

  /**
   * Gets the attribute value for the calculated attribute Business_problem.
   * @return the Business_problem
   */
  public Integer getBusiness_problem() {
    return (Integer) getAttributeInternal(BUSINESS_PROBLEM);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute Business_problem.
   * @param value value to set the  Business_problem
   */
  public void setBusiness_problem(Integer value) {
    setAttributeInternal(BUSINESS_PROBLEM, value);
  }

  /**
   * Gets the view accessor <code>RowSet</code> BusinessProblemLookupVO1.
   */
  public RowSet getBusinessProblemLookupVO1() {
    return (RowSet)getAttributeInternal(BUSINESSPROBLEMLOOKUPVO1);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
