package com.archemy.searchapp.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 14:29:15 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class KadTempVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public KadTempVOImpl() {
  }
}
