package com.archemy.searchapp.model.queries;

import java.math.BigDecimal;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 14 01:36:23 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SummaryUsageStatisticsVORowImpl extends ViewRowImpl {
  /**
   * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
   */
  public enum AttributesEnum {
    DeploymentStatus {
      public Object get(SummaryUsageStatisticsVORowImpl obj) {
        return obj.getDeploymentStatus();
      }

      public void put(SummaryUsageStatisticsVORowImpl obj, Object value) {
        obj.setDeploymentStatus((String)value);
      }
    }
    ,
    ApplicabilityExtent {
      public Object get(SummaryUsageStatisticsVORowImpl obj) {
        return obj.getApplicabilityExtent();
      }

      public void put(SummaryUsageStatisticsVORowImpl obj, Object value) {
        obj.setApplicabilityExtent((String)value);
      }
    }
    ,
    AvgBenefitRating {
      public Object get(SummaryUsageStatisticsVORowImpl obj) {
        return obj.getAvgBenefitRating();
      }

      public void put(SummaryUsageStatisticsVORowImpl obj, Object value) {
        obj.setAvgBenefitRating((BigDecimal)value);
      }
    }
    ,
    AvgMaturityRating {
      public Object get(SummaryUsageStatisticsVORowImpl obj) {
        return obj.getAvgMaturityRating();
      }

      public void put(SummaryUsageStatisticsVORowImpl obj, Object value) {
        obj.setAvgMaturityRating((BigDecimal)value);
      }
    }
    ,
    KadId {
      public Object get(SummaryUsageStatisticsVORowImpl obj) {
        return obj.getKadId();
      }

      public void put(SummaryUsageStatisticsVORowImpl obj, Object value) {
        obj.setKadId((Integer)value);
      }
    }
    ;
    private static AttributesEnum[] vals = null;
    private static int firstIndex = 0;

    public abstract Object get(SummaryUsageStatisticsVORowImpl object);

    public abstract void put(SummaryUsageStatisticsVORowImpl object, Object value);

    public int index() {
      return com.archemy.searchapp.model.queries.SummaryUsageStatisticsVORowImpl.AttributesEnum.firstIndex() + ordinal();
    }

    public static int firstIndex() {
      return firstIndex;
    }

    public static int count() {
      return com.archemy.searchapp.model.queries.SummaryUsageStatisticsVORowImpl.AttributesEnum.firstIndex() + com.archemy.searchapp.model.queries.SummaryUsageStatisticsVORowImpl.AttributesEnum.staticValues().length;
    }

    public static AttributesEnum[] staticValues() {
      if (vals == null) {
        vals = com.archemy.searchapp.model.queries.SummaryUsageStatisticsVORowImpl.AttributesEnum.values();
      }
      return vals;
    }
  }


  public static final int DEPLOYMENTSTATUS = AttributesEnum.DeploymentStatus.index();
  public static final int APPLICABILITYEXTENT = AttributesEnum.ApplicabilityExtent.index();
  public static final int AVGBENEFITRATING = AttributesEnum.AvgBenefitRating.index();
  public static final int AVGMATURITYRATING = AttributesEnum.AvgMaturityRating.index();
  public static final int KADID = AttributesEnum.KadId.index();

  /**
   * This is the default constructor (do not remove).
   */
  public SummaryUsageStatisticsVORowImpl() {
  }

  /**
   * Gets the attribute value for the calculated attribute DeploymentStatus.
   * @return the DeploymentStatus
   */
  public String getDeploymentStatus() {
    return (String) getAttributeInternal(DEPLOYMENTSTATUS);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute DeploymentStatus.
   * @param value value to set the  DeploymentStatus
   */
  public void setDeploymentStatus(String value) {
    setAttributeInternal(DEPLOYMENTSTATUS, value);
  }

  /**
   * Gets the attribute value for the calculated attribute ApplicabilityExtent.
   * @return the ApplicabilityExtent
   */
  public String getApplicabilityExtent() {
    return (String) getAttributeInternal(APPLICABILITYEXTENT);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute ApplicabilityExtent.
   * @param value value to set the  ApplicabilityExtent
   */
  public void setApplicabilityExtent(String value) {
    setAttributeInternal(APPLICABILITYEXTENT, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AvgBenefitRating.
   * @return the AvgBenefitRating
   */
  public BigDecimal getAvgBenefitRating() {
    return (BigDecimal) getAttributeInternal(AVGBENEFITRATING);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AvgBenefitRating.
   * @param value value to set the  AvgBenefitRating
   */
  public void setAvgBenefitRating(BigDecimal value) {
    setAttributeInternal(AVGBENEFITRATING, value);
  }

  /**
   * Gets the attribute value for the calculated attribute AvgMaturityRating.
   * @return the AvgMaturityRating
   */
  public BigDecimal getAvgMaturityRating() {
    return (BigDecimal) getAttributeInternal(AVGMATURITYRATING);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute AvgMaturityRating.
   * @param value value to set the  AvgMaturityRating
   */
  public void setAvgMaturityRating(BigDecimal value) {
    setAttributeInternal(AVGMATURITYRATING, value);
  }

  /**
   * Gets the attribute value for the calculated attribute KadId.
   * @return the KadId
   */
  public Integer getKadId() {
    return (Integer) getAttributeInternal(KADID);
  }

  /**
   * Sets <code>value</code> as the attribute value for the calculated attribute KadId.
   * @param value value to set the  KadId
   */
  public void setKadId(Integer value) {
    setAttributeInternal(KADID, value);
  }

  /**
   * getAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param attrDef the attribute

   * @return the attribute value
   * @throws Exception
   */
  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
    }
    return super.getAttrInvokeAccessor(index, attrDef);
  }

  /**
   * setAttrInvokeAccessor: generated method. Do not modify.
   * @param index the index identifying the attribute
   * @param value the value to assign to the attribute
   * @param attrDef the attribute

   * @throws Exception
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef) throws Exception {
    if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
      AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
      return;
    }
    super.setAttrInvokeAccessor(index, value, attrDef);
  }
}
