package com.archemy.searchapp.model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 14 01:36:23 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SummaryUsageStatisticsVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public SummaryUsageStatisticsVOImpl() {
  }

  /**
   * Returns the bind variable value for bkadId.
   * @return bind variable value for bkadId
   */
  public Integer getbkadId() {
    return (Integer)getNamedWhereClauseParam("bkadId");
  }

  /**
   * Sets <code>value</code> for bind variable bkadId.
   * @param value value to bind as bkadId
   */
  public void setbkadId(Integer value) {
    setNamedWhereClauseParam("bkadId", value);
  }
}
