# Fortress Connection to ApacheDS
host=localhost
port=10389
ldap.server.type=apacheds

apacheds.pwpolicy.root=ou=passwordPolicies,ads-interceptorId=authenticationInterceptor,ou=interceptors,ads-directoryServiceId=default,ou=config

disable.audit=true
enable.ldap.ssl=false
enable.ldap.ssl.debug=false
trust.store.onclasspath=false
enable.ldap.starttls=false

admin.user=uid=admin,ou=system
admin.pw=secret

min.admin.conn=1
max.admin.conn=10
min.user.conn=1
max.user.conn=10

min.log.conn=1
max.log.conn=3

config.realm=DEFAULT
config.root=ou=Config,dc=example,dc=com

debug.ldap.pool=true
enable.pool.reconnect=true

ehcache.config.file=ehcache.xml
disable.dsd.cache=false

enable.mgr.impl.rest=false

group.properties=ftProps
