package com.archemy.searchapp.model.am.client;

import com.archemy.searchapp.model.am.common.ArchemySearchAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 19:59:21 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArchemySearchAMClient extends ApplicationModuleImpl implements ArchemySearchAM {
  /**
   * This is the default constructor (do not remove).
   */
  public ArchemySearchAMClient() {
  }


  public void addKAD(int domainId) {
    Object _ret = this.riInvokeExportedMethod(this,"addKAD",new String [] {"int"},new Object[] {new Integer(domainId)});
    return;
  }


  public void searchAndRankKad(String businessProblem) {
    Object _ret =
      this.riInvokeExportedMethod(this,"searchAndRankKad",new String [] {"java.lang.String"},new Object[] {businessProblem});
    return;
  }


  public void addCustomerRowIfNotExists(String custId) {
    Object _ret =
      this.riInvokeExportedMethod(this,"addCustomerRowIfNotExists",new String [] {"java.lang.String"},new Object[] {custId});
    return;
  }

  public void addKAD(Integer domainId) {
    Object _ret = this.riInvokeExportedMethod(this,"addKAD",new String [] {"java.lang.Integer"},new Object[] {domainId});
    return;
  }

  public void changePasswordForUser(String userId, String password, String newPassword) {
    Object _ret =
      this.riInvokeExportedMethod(this,"changePasswordForUser",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, password, newPassword});
    return;
  }

  public void executeEmptyRowSet(String voName) {
    Object _ret =
      this.riInvokeExportedMethod(this,"executeEmptyRowSet",new String [] {"java.lang.String"},new Object[] {voName});
    return;
  }

  public Integer incrementHitCount(int kadId) {
    Object _ret = this.riInvokeExportedMethod(this,"incrementHitCount",new String [] {"int"},new Object[] {new Integer(kadId)});
    return (Integer)_ret;
  }

  public void insertKADTempRow() {
    Object _ret = this.riInvokeExportedMethod(this,"insertKADTempRow",null,null);
    return;
  }

  public void removeKAD(Integer kadId) {
    Object _ret =
      this.riInvokeExportedMethod(this,"removeKAD",new String [] {"java.lang.Integer"},new Object[] {kadId});
    return;
  }

  public void searchAndRankKad(Integer businessProblem) {
    Object _ret =
      this.riInvokeExportedMethod(this,"searchAndRankKad",new String [] {"java.lang.Integer"},new Object[] {businessProblem});
    return;
  }
}
