package com.archemy.searchapp.model.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 19:59:21 EST 2016
// ---------------------------------------------------------------------
public interface ArchemySearchAM extends ApplicationModule {


  void removeKAD(Integer kadId);

  void executeEmptyRowSet(String voName);


  Integer incrementHitCount(int kadId);

  void changePasswordForUser(String userId, String password, String newPassword);

  void addCustomerRowIfNotExists(String custId);

  void addKAD(Integer domainId);

  void searchAndRankKad(Integer businessProblem);

  void insertKADTempRow();
}
