package com.archemy.searchapp.model.lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 28 16:40:41 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AreaParentIdLookupVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public AreaParentIdLookupVOImpl() {
  }

  /**
   * Returns the variable value for bDimensionId.
   * @return variable value for bDimensionId
   */
  public Integer getbDimensionId() {
    return (Integer)ensureVariableManager().getVariableValue("bDimensionId");
  }

  /**
   * Sets <code>value</code> for variable bDimensionId.
   * @param value value to bind as bDimensionId
   */
  public void setbDimensionId(Integer value) {
    ensureVariableManager().setVariableValue("bDimensionId", value);
  }

  /**
   * Returns the variable value for bAreaId.
   * @return variable value for bAreaId
   */
  public Integer getbAreaId() {
    return (Integer)ensureVariableManager().getVariableValue("bAreaId");
  }

  /**
   * Sets <code>value</code> for variable bAreaId.
   * @param value value to bind as bAreaId
   */
  public void setbAreaId(Integer value) {
    ensureVariableManager().setVariableValue("bAreaId", value);
  }


  /**
   * Returns the variable value for bDimensionId1.
   * @return variable value for bDimensionId1
   */
  public Integer getbDimensionId1() {
    return (Integer)ensureVariableManager().getVariableValue("bDimensionId1");
  }

  /**
   * Sets <code>value</code> for variable bDimensionId1.
   * @param value value to bind as bDimensionId1
   */
  public void setbDimensionId1(Integer value) {
    ensureVariableManager().setVariableValue("bDimensionId1", value);
  }
}
