package com.archemy.searchapp.model.lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 13:59:43 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AreaChildLookupVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AreaChildLookupVOImpl() {
    }

    /**
     * Returns the bind variable value for bAreaParentId.
     * @return bind variable value for bAreaParentId
     */
    public Integer getbAreaParentId() {
        return (Integer)getNamedWhereClauseParam("bAreaParentId");
    }

    /**
     * Sets <code>value</code> for bind variable bAreaParentId.
     * @param value value to bind as bAreaParentId
     */
    public void setbAreaParentId(Integer value) {
        setNamedWhereClauseParam("bAreaParentId", value);
    }

  /**
   * Returns the variable value for bDimensionId.
   * @return variable value for bDimensionId
   */
  public Integer getbDimensionId() {
    return (Integer)ensureVariableManager().getVariableValue("bDimensionId");
  }

  /**
   * Sets <code>value</code> for variable bDimensionId.
   * @param value value to bind as bDimensionId
   */
  public void setbDimensionId(Integer value) {
    ensureVariableManager().setVariableValue("bDimensionId", value);
  }
}
