package com.archemy.searchapp.model.lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 18 18:10:13 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BusinessProblemLookupVOImpl extends ViewObjectImpl {
  /**
   * This is the default constructor (do not remove).
   */
  public BusinessProblemLookupVOImpl() {
  }
}
