package com.archemy.searchapp.model.lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 19:18:13 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DimensionsFilteredByDomainVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DimensionsFilteredByDomainVOImpl() {
    }

    /**
     * Returns the bind variable value for bDomainId.
     * @return bind variable value for bDomainId
     */
    public Integer getbDomainId() {
        return (Integer)getNamedWhereClauseParam("bDomainId");
    }

    /**
     * Sets <code>value</code> for bind variable bDomainId.
     * @param value value to bind as bDomainId
     */
    public void setbDomainId(Integer value) {
        setNamedWhereClauseParam("bDomainId", value);
    }
}
