package com.archemy.searchapp.model.lookups;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 10 14:53:59 EST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DomainLookupVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DomainLookupVOImpl() {
    }
}
